#:kivy 2.0.0
#:import win kivy.core.window.Window

<ShimejiGame>:
    drag_rectangle: self.x, self.y, self.width, self.height
    drag_timeout: 10000000
    drag_distance: 0
    orientation: 'vertical'

    canvas:
        Color:
            rgba: 0, 0, 0, 1
    BoxLayout:
        Image:
            id: catraView
            source: 'static/catra.png'
            background_color: 0, 0, 0, 1
            size: 410, 410
